// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNI3OJFoEOXRa2jxsQ5_WdTYDmFl6rrhA',
    appId: '1:673727832980:web:b1271d561a45914a9ae581',
    messagingSenderId: '673727832980',
    projectId: 'fir-ui-colorist',
    authDomain: 'fir-ui-colorist.firebaseapp.com',
    storageBucket: 'fir-ui-colorist.firebasestorage.app',
    measurementId: 'G-W1EM1WZQNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmsrbNmhAQJxlh5n1mtVq_d6hMZ4ZtuAM',
    appId: '1:673727832980:android:a59836b129d0c1919ae581',
    messagingSenderId: '673727832980',
    projectId: 'fir-ui-colorist',
    storageBucket: 'fir-ui-colorist.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9xTKd8EnPtkPjzYMoBkYQJyqLzARdNZQ',
    appId: '1:673727832980:ios:444c6faef66c83709ae581',
    messagingSenderId: '673727832980',
    projectId: 'fir-ui-colorist',
    storageBucket: 'fir-ui-colorist.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNI3OJFoEOXRa2jxsQ5_WdTYDmFl6rrhA',
    appId: '1:673727832980:web:1bae805733f65ee09ae581',
    messagingSenderId: '673727832980',
    projectId: 'fir-ui-colorist',
    authDomain: 'fir-ui-colorist.firebaseapp.com',
    storageBucket: 'fir-ui-colorist.firebasestorage.app',
    measurementId: 'G-HXQL5D5VZD',
  );
}
